# Generated by Django 4.1.2 on 2023-08-30 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(default=1, max_length=256)),
                ('clientName', models.TextField(default='')),
                ('IdNumber', models.TextField(default='')),
                ('BACNumber', models.TextField(default='')),
                ('supplier', models.TextField(blank=True, default='')),
                ('product', models.TextField(blank=True, default='')),
                ('businessType', models.IntegerField(default=0)),
                ('businessUnit', models.TextField(blank=True, default='')),
                ('categorisation', models.TextField(blank=True, default='')),
                ('advisorEmail', models.TextField(blank=True, default='')),
                ('supervisor', models.TextField(blank=True, default='')),
                ('region', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
