# Generated by Django 4.1.2 on 2023-08-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_compliancedocument_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='policy_number',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
