# Generated by Django 4.1.2 on 2023-08-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_rename_bacnumber_compliancedocument_bac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='advisor',
            field=models.CharField(blank=True, default=1, max_length=500),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='policy_number',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
