# Generated by Django 4.1.2 on 2023-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_alter_compliancedocument_advisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='advisor',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='businessUnit',
            field=models.IntegerField(default=1),
        ),
    ]
