# Generated by Django 4.1.2 on 2023-09-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compliance', '0007_alter_compliancedocument_advisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateKeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('lump_sum', models.TextField(blank=True, default='')),
                ('monthly_premium', models.TextField(blank=True, default='')),
                ('commission', models.TextField(blank=True, default='')),
                ('fica', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('proof_of_screening', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('dra', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('letter_of_intro', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('authorisation_letter', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('roa_type', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('roa', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('fna', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('application', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('quotation', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('risk_portfolio', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('mandate', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('replacement', models.IntegerField(blank=True, choices=[('100', 'Yes'), ('0', 'No'), ('-1', 'N/A')], default=0)),
                ('replacement_type', models.IntegerField(blank=True, choices=[('1', 'Rule 19'), ('0', 'Select'), ('2', 'Non rule 19')], default=0)),
                ('policy_schedule', models.TextField(blank=True, default='')),
                ('commission_release_form', models.TextField(blank=True, default='')),
                ('referral_reason', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(blank=True, choices=[('1', 'Approved'), ('2', 'Outstanding Requirements'), ('3', 'Referred')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(blank=True, choices=[('1', 'Approved'), ('2', 'Outstanding Requirements'), ('3', 'Referred')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.compliancedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
