# Generated by Django 4.1.2 on 2023-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_arc_questions_arc'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc_questions',
            name='max_score',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='arc_questions',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
