# Generated by Django 4.1.2 on 2023-09-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_arc_questions_max_score_arc_questions_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc_questions',
            name='max_score',
        ),
    ]
