# Generated by Django 4.1.2 on 2023-09-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_remove_arc_questions_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc_questions',
            name='max_score',
            field=models.IntegerField(default=15),
        ),
    ]
