# Generated by Django 4.1.2 on 2023-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_arc_questions_max_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='arc_question_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Main')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
