# Generated by Django 4.1.2 on 2023-09-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_arc_question_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc_questions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compliance.arc_question_header'),
            preserve_default=False,
        ),
    ]
