# Generated by Django 4.1.2 on 2023-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_arc_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='question',
            field=models.TextField(verbose_name=''),
        ),
    ]
