# Generated by Django 4.1.2 on 2023-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0015_alter_arc_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatekeeping',
            name='status',
            field=models.IntegerField(blank=True, choices=[('0', 'New Case'), ('1', 'Approved'), ('2', 'Outstanding Requirements'), ('3', 'Referred')], default=0),
        ),
    ]
