# Generated by Django 4.1.2 on 2023-09-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_alter_gatekeeping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatekeeping',
            name='application',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='authorisation_letter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='dra',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='fica',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='fna',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='letter_of_intro',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='mandate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='proof_of_screening',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='quotation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='replacement',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='replacement_type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='risk_portfolio',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='roa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gatekeeping',
            name='roa_type',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
