# Generated by Django 4.1.2 on 2023-09-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0019_compliancedocument_previous_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancedocument',
            name='businessUnit',
        ),
    ]
