# Generated by Django 4.1.2 on 2023-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0021_remove_arc_answer_remove_arc_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcomments',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
