# Generated by Django 4.1.2 on 2023-10-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0024_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='starting_point',
            field=models.IntegerField(default=2),
        ),
    ]
