# Generated by Django 4.1.2 on 2023-10-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0025_compliancedocument_starting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='picked_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='referred',
            field=models.BooleanField(default=False),
        ),
    ]
