# Generated by Django 4.1.2 on 2023-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0026_compliancedocument_picked_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatekeeping',
            name='disclosure',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gatekeeping',
            name='identity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
