# Generated by Django 4.1.2 on 2023-10-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0027_gatekeeping_disclosure_gatekeeping_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedocument',
            name='commission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='lump_sum',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='monthly_premium',
            field=models.TextField(blank=True, default=''),
        ),
    ]
