# Generated by Django 4.1.2 on 2023-11-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0028_compliancedocument_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancedocument',
            name='advisor',
            field=models.IntegerField(default=0),
        ),
    ]
