# Generated by Django 4.1.2 on 2023-11-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0029_alter_compliancedocument_advisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatekeeping',
            old_name='disclosure',
            new_name='date_of_screening',
        ),
        migrations.RenameField(
            model_name='gatekeeping',
            old_name='identity',
            new_name='timeously',
        ),
    ]
