# Generated by Django 4.0.6 on 2022-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=256)),
                ('client_id', models.CharField(max_length=256)),
                ('client_address', models.CharField(max_length=256)),
                ('client_email', models.CharField(max_length=256)),
                ('client_date_of_birth', models.DateField()),
                ('client_letter_of_introduction', models.BooleanField(default=False)),
                ('client_letter_of_introduction_reason', models.CharField(max_length=256)),
                ('client_fica', models.BooleanField(default=False)),
                ('client_fica_reason', models.CharField(max_length=256)),
                ('client_background_info', models.CharField(max_length=1000)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
