# Generated by Django 4.0.6 on 2022-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='client_fica_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='client_letter_of_introduction_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
