# Generated by Django 4.0.6 on 2022-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_form_client_fica_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.IntegerField(default=1),
        ),
    ]
