# Generated by Django 4.1.2 on 2024-01-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notifications_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='planName',
        ),
    ]
