# Generated by Django 4.1.2 on 2023-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('expires', models.BooleanField(default=False)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
