# Generated by Django 4.1.2 on 2023-11-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='api_key',
            field=models.TextField(),
        ),
    ]
