version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    container_name: sfp-db
    volumes:
      - sfp-postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  # web:
  #   # build: 
  #   #   context: ./backend
  #   #   dockerfile: Dockerfile
  #   image: kaspar.azurecr.io/kaspar_sfproa_backend
  #   container_name: sfp_backend
  #   # command: python /app/manage.py runserver 0.0.0.0:8000
  #   command: gunicorn sfp.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  #     - /app
  #     - sfp_static_files:/app/static/
  #   restart:
  #     always
  #   expose:
  #     - 8000
  #   # ports:
  #   #   - "8001:8000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db
  #   links:
  #     - db:db
    
  # web_migration:
  #   image: kaspar.azurecr.io/kaspar_sfproa_backend
  #   # build: 
  #   #   context: .
  #   #   dockerfile: Dockerfile.backend
  #   command: python /app/manage.py migrate
  #   volumes:
  #     - sfp_static_files:/app
  #   # expose:
  #   #   - 8000
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - web

  # frontend:
  #   image: kaspar.azurecr.io/kaspar_sfproa_frontend
  #   # build:
  #   #   context: ./frontend
  #   #   dockerfile: Dockerfile 
  #   container_name: sfp_frontend
  #   # command: npm start
  #   ports:
  #     - 3000
  #   depends_on:
  #     - web
  #   restart: always
      

  pgadmin:
    image: dpage/pgadmin4
    container_name: sfp-pgadmin #you can change this
    depends_on:
      - db
    ports:
      - 5050
    env_file:
      - ./.env
    restart: always

  # nginx:
  #   # build: 
  #   #   context: ./nginx
  #   image: kaspar.azurecr.io/django-nginx
  #   container_name: sfp_backend_nginx
  #   volumes:
  #     - sfp-static-files:/app/static/
  #   ports:
  #     - 8000
  #   depends_on:
  #     - web
  #   links:
  #     - web:web
  #   restart: always

volumes:
  sfp-postgres-data:
    driver: azure_file
    driver_opts:
      share_name: kasparsfp
      storage_account_name: kasparsfproa
  # sfp-static-files:
  #   driver: azure_file
  #   driver_opts:
  #     share_name: kasparsfp
  #     storage_account_name: kasparsfproa
