# Generated by Django 4.1.2 on 2022-10-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_fiduciaryExecutorDetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiduciary',
            name='fiduciaryExecutor',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
    ]
