# Generated by Django 4.1.2 on 2022-10-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_fiduciaryExecutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryExecutor',
            field=models.CharField(max_length=500),
        ),
    ]
