# Generated by Django 4.1.2 on 2022-10-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_fiduciaryExecutor1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiduciary',
            old_name='fiduciaryExecutorDetail',
            new_name='fiduciaryExecutorDetails',
        ),
        migrations.RemoveField(
            model_name='fiduciary',
            name='fiduciaryExecutor',
        ),
    ]
