# Generated by Django 4.1.2 on 2022-10-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_fiduciaryExecutor2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiduciary',
            name='clientIdNumber',
        ),
        migrations.RemoveField(
            model_name='investmentplanning',
            name='clientIdNumber',
        ),
    ]
