# Generated by Django 4.1.2 on 2022-10-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_noMoreClientId'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_IncomeRequiredDetails',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_LiquidityDetails',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_PremiumTypeDetails',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_TypeDetails',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
    ]
