# Generated by Django 4.1.2 on 2022-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_hmmmv1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_AltS_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_AltS_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_AltS_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_CR_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_CR_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_CR_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_CR_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_FinancialSolutions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Other_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Other_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Other_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Other_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_MaterialAspects',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_NominationOfBeneficiaries',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Pr_Details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Reasons',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Portfolio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_Beneficiary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_ContractingParty',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_EAC',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_Escalation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_IniC',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_IniC_Percentage',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_LivesAssured',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_Name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_OnC',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_OnC_Percentage',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_PolicyNumber',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_Premium',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_PremiumLayer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Pr_Provider',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_RA_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_RA_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_RA_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_RA_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_ReturnRequiredDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_RiskProfileDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_StrategyDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_TRP_ExistingInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_TRP_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_TRP_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_TRP_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Term',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_TermDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_AltS_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_AltS_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_AltS_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_CoverAmount1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_CoverAmount2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_CoverAmount3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_CoverAmount4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_CoverAmount5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_CoverAmount6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BenDesc_CoverAmount7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DeathAssuranceInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DeathProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DeathShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DeathTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DiC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DiC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DiC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_DiC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_OtherExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_OtherExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_OtherInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BnS_OtherTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusA_Details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_OtherExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_OtherExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_OtherInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_OtherTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_PI_CoverExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_PI_CoverExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_PI_CoverInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_PI_CoverTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_TI_CoverExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_TI_CoverExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_TI_CoverInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusOvProt_TI_CoverTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessAddress',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessAuthorisedPersons',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessDate',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessEmail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessFinancialAdvisor',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessPhoneNumber',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessRegisteredName',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_BusinessTradeName',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DiC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DiC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DiC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_DiC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_Cessionaries',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ComDisc_AuthorityDetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ComDisc_AuthorizedPersonDetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DiC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DiC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DiC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_DiC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_DiC_FinancialSolutions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_FICADetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_InformationExplained',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DiC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DiC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DiC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_DiC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_OtherExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_OtherExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_OtherInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_OtherTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_PI_CoverExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_PI_CoverExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_PI_CoverInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_PI_CoverTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_TI_CoverExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_TI_CoverExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_TI_CoverInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_KeyP_TI_CoverTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_LifeCoverFinancialSolutions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_PolicyNumber',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_Product1stYearCommission',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_Product2ndYearCommission',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductBriefSummary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductContractingParty',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductEscalation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductLivesAssured',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductMaterialAspects',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductName',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductOngoingFees',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductOngoingFeesFrequency',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductPattern',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductPremium',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductPremiumPayer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductProvider',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ProductReasons',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_RepPrs_CancelledDetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_RepPrs_TakenDetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_ReplacementBackInfo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SourceOfFundsDetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathAssuranceInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DiC_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DiC_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DiC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_DiC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryClientInstructions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryConsequencesExplained',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryExecutorDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryWillKeepingPlace',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryWillUpdationDate',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientFicaReason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientLetterOfIntroductionAccessReason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientLetterOfIntroductionReason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_AltS_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_AltS_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_AltS_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_IncomeRequiredDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_InvestmentStrategyDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_InvestmentTerm',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_InvestmentTermDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_Fund7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundPercentage7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundsMaterialAspects',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ItP_FundsReasons',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_LiquidityDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_OtherSourceOfIncome',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_PolicyNumber',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_PremiumTypeDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductBeneficiary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductContractingParty',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductEAC',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductEscalation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductLivesAssured',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductName',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductPremium',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductPremiumLayer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ProductProvider',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_Product_IniC',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_Product_IniC_Percentage',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_Product_OnC',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_Product_OnC_Percentage',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_RecommendationSummary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_ReturnRequiredDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_RiskProfileDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_SFPSolutionFundsDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='IP_TypeDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RPDreadComments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RPLifeCoverFinancialSolutions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_AltS_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_AltS_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_AltS_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_FB_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_FB_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_FB_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_FB_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_IncomeExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_IncomeExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_IncomeInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_IncomeTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_LumpSumExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_LumpSumExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_LumpSumInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_LumpSumTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_OtherExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_OtherExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_OtherInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DC_OtherTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_Comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_FinancialSolutions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_LumpSumExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_LumpSumExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_LumpSumInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_LumpSumTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherExistingProvisions1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherExistingProvisions2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherExistingShortfallSurplus1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherExistingShortfallSurplus2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherInvestments1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherInvestments2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherTotalNeed1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_OtherTotalNeed2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_PI_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_PI_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_PI_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_PI_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_SiB_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_SiB_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_SiB_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_SiB_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_TI_ExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_TI_ExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_TI_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DiC_TI_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_FinancialSolutions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_IncomeExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_IncomeExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_IncomeInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_IncomeTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_LumpSumExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_LumpSumExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_LumpSumInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_LumpSumTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherExistingProvisions1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherExistingProvisions2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherExistingShortfallSurplus1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherExistingShortfallSurplus2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherExistingriskPlannings2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherInvestments1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherTotalNeed1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_DrC_OtherTotalNeed2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_ExecutorFee',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_InformationExplained',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_NominationOfBeneficiaries',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Policy_Number',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_ProductDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_ProductMaterialAspects',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_ProductReasons',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_1stYearCommission',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_2ndYearCommission',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_Beneficiary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_ContractingParty',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_Escalation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_LivesAssured',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_Name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_OngoingFees',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_OngoingFeesFrequency',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_Pattern',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_Premium',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_PremiumPayer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_Provider',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_TotalFees_n_Commissions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
