# Generated by Django 4.1.2 on 2022-10-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskplanning',
            old_name='RP_DrC_OtherExistingriskPlannings2',
            new_name='RP_DrC_OtherInvestments2',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='clientIdNumber',
        ),
    ]
