# Generated by Django 4.1.2 on 2022-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_update1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_General_History',
            field=models.JSONField(default={}, max_length=2048),
        ),
    ]
