# Generated by Django 4.1.2 on 2022-10-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_update1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskplanning',
            old_name='RPDreadComments',
            new_name='RP_DrC_Comments',
        ),
    ]
