# Generated by Django 4.1.2 on 2022-10-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_update1'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskplanning',
            name='RP_Product_OngoingFeesFrequency1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
