# Generated by Django 4.1.2 on 2022-10-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_update1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_OngoingFeesFrequency1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='RP_Product_PremiumFrequency',
            field=models.IntegerField(default=1),
        ),
    ]
