# Generated by Django 4.1.2 on 2022-10-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_update1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Type',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_TypeDetails',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='clientIdNumber',
        ),
    ]
