# Generated by Django 4.1.2 on 2022-10-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_update1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_Taken',
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PremiumTypeDetails',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
