# Generated by Django 4.1.2 on 2022-10-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_update2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assuranceinvestment',
            old_name='AI_CR_Investments',
            new_name='AI_CR_ExistingInvestments',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Other_Investments',
        ),
        migrations.AddField(
            model_name='assuranceinvestment',
            name='AI_Other_ExistingInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
