# Generated by Django 4.1.2 on 2022-10-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_update2_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathAssuranceInvestments',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathProvisions',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathShortfallSurplus',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_DeathTotalNeed',
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_AssuranceInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_Provisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_ShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
