# Generated by Django 4.1.2 on 2022-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_update2_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_BnS_DeathAssuranceInvestments',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_BnS_DeathProvisions',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_BnS_DeathShortfallSurplus',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_BnS_DeathTotalNeed',
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BnS_DC_AssuranceInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BnS_DC_Provisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BnS_DC_ShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BnS_DC_TotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
