# Generated by Django 4.1.2 on 2022-10-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_update2_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_BnS_DC_AssuranceInvestments',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_AssuranceInvestments',
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BnS_DC_Investment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_Investment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
