# Generated by Django 4.1.2 on 2022-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_update2_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_RepPrs_Explained',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_RepPrs_ExplainedDetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
