# Generated by Django 4.1.2 on 2022-10-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_update2_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverExistingProvisions',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverExistingShortfallSurplus',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverInvestments',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_CLARedm_TI_CoverTotalNeed',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverExistingProvisions',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverExistingShortfallSurplus',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverInvestments',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_DLARedm_TI_CoverTotalNeed',
        ),
    ]
