# Generated by Django 4.1.2 on 2022-10-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_update2_7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_CLARedm_Comments',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_DLARedm_Comments',
        ),
    ]
