# Generated by Django 4.1.2 on 2022-10-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_update2_8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_ProductOngoingFees',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_ProductOngoingFeesFrequency',
        ),
    ]
