# Generated by Django 4.1.2 on 2022-10-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_update2_10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_BnS_DC_Investment',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_Investment',
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BnS_DC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_DC_Investments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
