# Generated by Django 4.1.2 on 2022-10-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_update2_1_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebenefits',
            name='EB_BusRB_DreadDiseaseCoverReason',
        ),
        migrations.RemoveField(
            model_name='employeebenefits',
            name='EB_BusRB_DreadDiseaseCoverSummary',
        ),
        migrations.RemoveField(
            model_name='employeebenefits',
            name='clientIdNumber',
        ),
        migrations.AddField(
            model_name='employeebenefits',
            name='EB_BusRB_DrC_Reason',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='employeebenefits',
            name='EB_BusRB_DrC_Summary',
            field=models.CharField(default='', max_length=256),
        ),
    ]
