# Generated by Django 4.1.2 on 2022-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_update2_1_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusB_CoverDetails',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEmp_AdditionalComments',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEmp_Fin_IlliteratePercentage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEmp_Fin_SophisticatedPercentage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEmp_Retire_In5YearsPercentage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEx_FundsActiveMembers',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEx_FundsAdmin',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEx_FundsCurrentValue',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEx_FundsFullyPaidMembers',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEx_FundsFullyReasonForChange',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusEx_FundsName',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_AdminC_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_AdminC_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_AdminFee_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_AdminFee_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenA_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenA_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayD_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayD_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayDis_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayDis_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayRe_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayRe_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayW_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_BenPayW_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_CoR_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_CoR_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_ConvOp_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_ConvOp_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_EligGr_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_EligGr_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_EmpContrib_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_EmpContrib_PercentageExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_EmpContrib_PercentageProposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_EmpContrib_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_FeeChargesExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_FeeChargesReplaced',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_HealthChangesExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_HealthChangesReplaced',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_HouseL_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_HouseL_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_InvestCh_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_InvestCh_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_InvestFee_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_InvestFee_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_MaterialDifferencesExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_MaterialDifferencesReplaced',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_MemContrib_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_MemContrib_Proposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_Name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_NormRetire_AgeExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_NormRetire_AgeProposed',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_PenaltiesExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_PenaltiesReplaced',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_RealisedExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_RealisedReplaced',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_RegNo',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_TaxImplicationsExisting',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_TaxImplicationsReplaced',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_TnC_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_TnC_Replaced',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusFReplace_Type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusHS_TurnOverPercentage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusI_ChoicePercentage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_AccidentBenefitCategory1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_AccidentBenefitCategory2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_AccidentBenefitCategory3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_AccidentBenefitCategory4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_AccidentBenefitReason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_ApprovedCategory1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_ApprovedCategory2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_ApprovedCategory3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_ApprovedCategory4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_ApprovedCategory1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_ApprovedCategory2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_ApprovedCategory3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_ApprovedCategory4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_UnApprovedCategory1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_UnApprovedCategory2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_UnApprovedCategory3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_CapDisBen_UnApprovedCategory4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_Category1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_Category2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_Category3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_Category4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_ConvOp',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiC_Reason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DisabilityBenefitsNotes',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DrC_Reason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DrC_Summary',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_EmpContrib_Category1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_EmpContrib_Category2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_EmpContrib_Category3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_EmpContrib_Category4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_FB_CoverCategory1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_FB_CoverCategory2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_FB_CoverCategory3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_FB_CoverCategory4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_FlexibleGroupLife',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_GrowthRates',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_MemContrib_Category1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_MemContrib_Category2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_MemContrib_Category3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_MemContrib_Category4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_NormRetire_AgeCategory1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_NormRetire_AgeCategory2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_NormRetire_AgeCategory3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_NormRetire_AgeCategory4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_SpouseLC_Category1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_SpouseLC_Category2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_SpouseLC_Category3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_SpouseLC_Category4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_SpouseLC_Notes',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_TrauBenSa_Category1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_TrauBenSa_Category2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_TrauBenSa_Category3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_TrauBenSa_Category4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_UnApprovedCategory1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_UnApprovedCategory2',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_UnApprovedCategory3',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_UnApprovedCategory4',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRecom_ClientRisks',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRecom_FundType',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRecom_ProductAdmin',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRecom_ProductName',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRecom_RecommendationFundType',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessAddress',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessCellNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessContactPerson',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessDetails',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessEmail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessItP_Percentage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessName',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessNature',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessNumberOfEligibleEmployees',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessNumberOfEmployees',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessNumberOfExcludedCategories',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusinessPhoneNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientAddress',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientCellNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientDate',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientEmail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientFeeDetails',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientFinancialAdvisor',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientIdNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientName',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_ClientPhoneNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Applicable_Option',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Branch_Name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Branch_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BuildCombined_ColumnRef',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BuildCombined_Desc',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BuildCombined_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Buildings_Insured',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Basis',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Indemnity',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_PremiseNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Wages1',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Business_Description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Business_Owner',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_CellPhone_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Client_Id_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Company_Reg_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Company_VAT_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Contact_Person',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Email',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Extensions_Geysers',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Extensions_IorE',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Extensions_PoA',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Extensions_RnS',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Extensions_SnL',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fax_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_AdvisorComm_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_AdvisorComm_Replacement',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_Excesses_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_Excesses_Replacement',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_FnC_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_FnC_Replacement',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_ImpOnPre_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_ImpOnPre_Replacement',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_STnC_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_STnC_Replacement',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_VABen_Existing',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Fin_VABen_Replacement',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_General_Cancelled_Detail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Inception_Date',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Miscellaneous1_Insured',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Miscellaneous2_Insured',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_Desc',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_Doc_Premium',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_Doc_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_LLDoc_Premium',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_LLDoc_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_PremisesNum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_RnS_Premium',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_RnS_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_TheftF_Premium',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_TheftF_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_Theft_Premium',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_Theft_Sum',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_OC_Total_Premium',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Others_Insured',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Postal_Address',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Quotation_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Renewal_Date',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Rental_Insured',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Replacement_Advise_Details',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Replacement_Reason',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Replacement_Suppliers',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Risk_Address',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Stocks_Insured',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_TelePhone_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Underwritten_By',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='clientIdNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Applicant_Initials',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Applicant_Surname',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Applicant_Title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Branch_Name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Branch_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Inception_Date',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Policy_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Quotation_Number',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Underwritten_By',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='clientIdNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
