# Generated by Django 4.1.2 on 2022-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_update2_1_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapcover',
            name='GP_Option',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
