# Generated by Django 4.1.2 on 2022-11-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_update2_1_8'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapcover',
            name='GP_CP_GenWait_P',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='gapcover',
            name='GP_CP_PreExist_P',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='gapcover',
            name='GP_CP_Specific_P',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='gapcover',
            name='GP_NP_GenWait_P',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='gapcover',
            name='GP_NP_PreExist_P',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='gapcover',
            name='GP_NP_Specific_P',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gapcover',
            name='GP_FinanAdvisor_Date',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gapcover',
            name='GP_FinanAdvisor_FeeCommission',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gapcover',
            name='GP_FinanAdvisor_OtherComments',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
