# Generated by Django 4.1.2 on 2022-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_update2_2_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec13_33',
        ),
        migrations.RemoveField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec8_Extension_Included3',
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type12',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type22',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type22_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type23',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type23_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type2_12',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type2_22',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type2_22_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type2_23',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_Type2_23_1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted36',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted37',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted38',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted39',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted40',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted41',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted42',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Accepted43',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount36',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount37',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount38',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount39',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount40',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount41',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount42',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_CoverAmount43',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess36',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess37',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess38',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess39',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess40',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess41',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess42',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Excess43',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium36',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium37',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium38',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium39',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium40',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium41',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium42',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Premium43',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess36',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess37',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess38',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess39',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess40',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess41',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess42',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Excess43',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium36',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium37',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium38',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium39',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium40',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium41',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium42',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_RecommP_Premium43',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended36',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended37',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended38',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended39',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended40',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended41',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended42',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_Recommended43',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_9',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit6',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit7',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit8',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionLimit9',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium6',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium7',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium8',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec17_ExtensionPremium9',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
