# Generated by Django 4.1.2 on 2022-11-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_update2_2_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortTermInsurancePersonal',
        ),
    ]
