# Generated by Django 4.1.2 on 2022-11-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_update2_2_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_Vehicle_Extras14',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
