# Generated by Django 4.1.2 on 2022-11-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_update2_2_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_LegalA_IndemnityLimitDetail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_PersonalLL_IndemnityLimitDetail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
