# Generated by Django 4.1.2 on 2022-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_update2_2_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskplanning',
            name='RP_DC_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='riskplanning',
            name='RP_DiC_Other1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='riskplanning',
            name='RP_DiC_Other2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='riskplanning',
            name='RP_DrC_Other1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='riskplanning',
            name='RP_DrC_Other2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
