# Generated by Django 4.1.2 on 2022-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_update2_2_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BnS_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_BusOvProt_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_CLARedm_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_DLARedm_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_KeyP_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
