# Generated by Django 4.1.2 on 2022-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_update2_2_8'),
    ]

    operations = [
        migrations.AddField(
            model_name='assuranceinvestment',
            name='AI_SourceOfFunds',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assuranceinvestment',
            name='AI_SourceOfFundsDetail',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
