# Generated by Django 4.1.2 on 2022-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_update2_2_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='assuranceinvestment',
            name='AI_Other',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
