# Generated by Django 4.1.2 on 2022-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_update2_3_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='firstLogin',
            field=models.BooleanField(default=True),
        ),
    ]
