# Generated by Django 4.1.2 on 2022-12-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_useraccount_firstlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='firstLogin',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
