# Generated by Django 4.1.2 on 2023-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_remove_useraccount_firstlogin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField()),
                ('RF_BU_Risk', models.CharField(blank=True, default='', max_length=250)),
                ('RF_Date', models.DateField()),
                ('RF_ClientName', models.CharField(blank=True, default='', max_length=250)),
                ('RF_CompleteByName', models.CharField(blank=True, default='', max_length=250)),
                ('RF_CompleteByRole', models.CharField(blank=True, default='', max_length=250)),
                ('RF_ClientType', models.IntegerField(default=1)),
                ('RF_Occupation', models.IntegerField(default=1)),
                ('RF_CountryOfBirth', models.IntegerField(default=1)),
                ('RF_CountryOfResidence', models.IntegerField(default=1)),
                ('RF_Nationality', models.IntegerField(default=1)),
                ('RF_Different_Nationality', models.IntegerField(default=1)),
                ('RF_CountryOfTax', models.IntegerField(default=1)),
                ('RF_Industry', models.IntegerField(default=1)),
                ('RF_SourceOfFunds', models.IntegerField(default=1)),
                ('RF_RelationshipToClient', models.IntegerField(default=1)),
                ('RF_CountryOfRegistration', models.IntegerField(default=1)),
                ('RF_CountryOfOperation', models.IntegerField(default=1)),
                ('RF_Type_Legal_Entity', models.IntegerField(default=1)),
                ('RF_Client_Relationship', models.IntegerField(default=1)),
                ('RF_Product_Name', models.IntegerField(default=1)),
                ('RF_Transaction_Flow', models.IntegerField(default=1)),
                ('RF_Transaction_Method', models.IntegerField(default=1)),
                ('RF_Transaction_Reason', models.IntegerField(default=1)),
                ('RF_High_Transaction_Reason', models.IntegerField(default=1)),
                ('RF_Transaction_Frequency', models.IntegerField(default=1)),
                ('RF_Transaction_Value', models.IntegerField(default=1)),
                ('RF_Currency_Value', models.IntegerField(default=1)),
                ('RF_Transaction_Geography', models.IntegerField(default=1)),
                ('RF_Funds_Jurisdiction', models.IntegerField(default=1)),
                ('RF_Delivery_Channel', models.IntegerField(default=1)),
                ('RF_Linked_Party_Acting', models.IntegerField(default=1)),
                ('RF_Linked_Party_Paying', models.IntegerField(default=1)),
                ('RF_Client_Match', models.IntegerField(default=1)),
                ('RF_Client_Beneficiaries', models.IntegerField(default=1)),
                ('RF_Adjust_Risk1', models.IntegerField(default=1)),
                ('RF_Name', models.CharField(blank=True, default='', max_length=250)),
                ('RF_ID', models.CharField(blank=True, default='', max_length=250)),
                ('RF_Linked_Party', models.IntegerField(default=1)),
                ('RF_RCA', models.IntegerField(default=1)),
                ('RF_Birth_Country', models.IntegerField(default=1)),
                ('RF_Residence_Country', models.IntegerField(default=1)),
                ('RF_Nationality1', models.IntegerField(default=1)),
                ('RF_Control1', models.CharField(blank=True, default='', max_length=250)),
                ('RF_Control2', models.CharField(blank=True, default='', max_length=250)),
                ('RF_Control3', models.CharField(blank=True, default='', max_length=250)),
                ('RF_Another_Control1', models.IntegerField(default=1)),
                ('RF_Another_Control2', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='formId',
            field=models.IntegerField(default=1),
        ),
    ]
