# Generated by Django 4.1.2 on 2023-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_RF'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='RF_ClientId',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
