# Generated by Django 4.1.2 on 2023-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_RF'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='RF_Overall_Risk',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
