# Generated by Django 4.1.2 on 2023-02-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_RF_Overall_Risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Adjust_Risk1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Another_Control1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Another_Control2',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Birth_Country',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_ClientType',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Client_Beneficiaries',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Client_Match',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Client_Relationship',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_CountryOfBirth',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_CountryOfOperation',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_CountryOfRegistration',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_CountryOfResidence',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_CountryOfTax',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Currency_Value',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Delivery_Channel',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Different_Nationality',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Funds_Jurisdiction',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_High_Transaction_Reason',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Industry',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Linked_Party',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Linked_Party_Acting',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Linked_Party_Paying',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Nationality',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Nationality1',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Occupation',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Product_Name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_RCA',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_RelationshipToClient',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Residence_Country',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_SourceOfFunds',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Transaction_Flow',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Transaction_Frequency',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Transaction_Geography',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Transaction_Method',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Transaction_Reason',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Transaction_Value',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='RF_Type_Legal_Entity',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
