# Generated by Django 4.1.2 on 2023-02-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_RF_Overall_Risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='clientAddress',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientEmail',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientIdNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientPhoneNumber',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
