# Generated by Django 4.1.2 on 2023-02-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_ROA_Model_Update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='clientDateOfBirth',
            field=models.DateField(blank=True, default=''),
        ),
    ]
