# Generated by Django 4.1.2 on 2023-02-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_ROA_Model_Update2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='clientBackgroundInfo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
