# Generated by Django 4.1.2 on 2023-03-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_ROA_Model_Update2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeebenefits',
            old_name='EB_BusRecom_Porfolio',
            new_name='EB_BusRecom_Portfolio',
        ),
    ]
