# Generated by Django 4.1.2 on 2023-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_rename_eb_busrecom_porfolio_employeebenefits_eb_busrecom_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_General_RefusedDetails',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_General_RisksDetails',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
