# Generated by Django 4.1.2 on 2023-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_alter_shortterminsurancepersonal_stip_general_refuseddetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='RF_Product_Category',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
