# Generated by Django 4.1.2 on 2023-03-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0065_riskfactors_rf_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='clientFicaReason',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientLetterOfIntroductionAccessReason',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientLetterOfIntroductionReason',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
