# Generated by Django 4.1.2 on 2023-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_alter_employeebenefits_eb_busb_coverdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='SNA_Other',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
