# Generated by Django 4.1.2 on 2023-03-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0071_remove_useraccount_partial_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
