# Generated by Django 4.1.2 on 2023-03-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_remove_useraccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_TotalPremium2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
