# Generated by Django 4.1.2 on 2023-03-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_shortterminsurancecommerical_stic_busint_totalpremium2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortterminsurancecommerical',
            name='STIC_BusInt_TotalPremium2',
        ),
    ]
