# Generated by Django 4.1.2 on 2023-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0074_remove_shortterminsurancecommerical_stic_busint_totalpremium2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_Sec14_Recommended2',
            field=models.IntegerField(default=1),
        ),
    ]
