# Generated by Django 4.1.2 on 2023-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_remove_shortterminsurancepersonal_stip_backinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assuranceinvestment',
            name='AI_Pr_Taken',
            field=models.IntegerField(default=1),
        ),
    ]
