# Generated by Django 4.1.2 on 2023-04-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_assuranceinvestment_ai_pr_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RF_LinkedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('RF_LP_Adjust_Risk', models.CharField(blank=True, default='', max_length=250)),
                ('RF_LP_Name', models.CharField(blank=True, default='', max_length=250)),
                ('RF_LP_Client_Relationship', models.IntegerField(default=0)),
                ('RF_LP_ID', models.CharField(blank=True, default='', max_length=250)),
                ('RF_LP_Linked_Party', models.IntegerField(default=0)),
                ('RF_LP_RCA', models.IntegerField(default=0)),
                ('RF_LP_Birth_Country', models.IntegerField(default=0)),
                ('RF_LP_Residence_Country', models.IntegerField(default=0)),
                ('RF_LP_Nationality', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Adjust_Risk1',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Another_Control1',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Another_Control2',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Birth_Country',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Control1',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Control2',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Control3',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_ID',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Linked_Party',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Name',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Nationality1',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_RCA',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='RF_Residence_Country',
        ),
    ]
