# Generated by Django 4.1.2 on 2023-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0078_rf_linkedparty_remove_riskfactors_rf_adjust_risk1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RP_ProductTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('Product_Taken', models.CharField(blank=True, default='', max_length=500)),
                ('Product_Provider', models.CharField(blank=True, default='', max_length=500)),
                ('Policy_Number', models.CharField(blank=True, default='', max_length=500)),
                ('Product_Name', models.CharField(blank=True, default='', max_length=500)),
                ('Product_Premium', models.CharField(blank=True, default='', max_length=500)),
                ('Product_PremiumFrequency', models.IntegerField(default=0)),
                ('Product_Pattern', models.CharField(blank=True, default='', max_length=500)),
                ('Product_Escalation', models.CharField(blank=True, default='', max_length=500)),
                ('Product_ContractingParty', models.CharField(blank=True, default='', max_length=500)),
                ('Product_LivesAssured', models.CharField(blank=True, default='', max_length=500)),
                ('Product_Beneficiary', models.CharField(blank=True, default='', max_length=500)),
                ('Product_PremiumPayer', models.CharField(blank=True, default='', max_length=500)),
                ('Product_1stYearCommission', models.CharField(blank=True, default='', max_length=500)),
                ('Product_2ndYearCommission', models.CharField(blank=True, default='', max_length=500)),
                ('Product_OngoingFees', models.CharField(blank=True, default='', max_length=500)),
                ('Product_OngoingFeesFrequency', models.CharField(blank=True, default='', max_length=500)),
                ('Product_OngoingFeesFrequency1', models.IntegerField(default=0)),
                ('TotalFees_n_Commissions', models.CharField(blank=True, default='', max_length=500)),
                ('ProductReasons', models.CharField(blank=True, default='', max_length=2000)),
                ('ProductMaterialAspects', models.CharField(blank=True, default='', max_length=2000)),
                ('ProductDetails', models.CharField(blank=True, default='', max_length=2000)),
                ('ExecutorFee', models.CharField(blank=True, default='', max_length=2000)),
                ('NominationOfBeneficiaries', models.CharField(blank=True, default='', max_length=2000)),
                ('InformationExplained', models.CharField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RP_ProductTaken_BenDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('productTakenId', models.IntegerField(default=0)),
                ('BenDesc', models.CharField(blank=True, default='', max_length=500)),
                ('BenDesc_CoverAmount', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_1',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_2',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_3',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_4',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_5',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_6',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_7',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount1',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount2',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount3',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount4',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount5',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount6',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_BenDesc_CoverAmount7',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_ExecutorFee',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_InformationExplained',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_NominationOfBeneficiaries',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Policy_Number',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_ProductDetails',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_ProductMaterialAspects',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_ProductReasons',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_1stYearCommission',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_2ndYearCommission',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_Beneficiary',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_ContractingParty',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_Escalation',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_LivesAssured',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_Name',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_OngoingFees',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_OngoingFeesFrequency',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_OngoingFeesFrequency1',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_Pattern',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_Premium',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_PremiumFrequency',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_PremiumPayer',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_Provider',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_Product_Taken',
        ),
        migrations.RemoveField(
            model_name='riskplanning',
            name='RP_TotalFees_n_Commissions',
        ),
    ]
