# Generated by Django 4.1.2 on 2023-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_rp_producttaken_rp_producttaken_bendesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_6',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_7',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
