# Generated by Django 4.1.2 on 2023-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0082_ar_producttaken_remove_assurancerisk_ar_bendesc_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_ProductTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('Pr_Taken', models.IntegerField(default=1)),
                ('Pr_Provider', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_PolicyNumber', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_Name', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_Premium', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_PremiumFrequency', models.IntegerField(default=1)),
                ('Pr_Escalation', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_EAC', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_ContractingParty', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_LivesAssured', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_PremiumPayer', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_Beneficiary', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_IniC', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_IniC_Percentage', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_OnC', models.CharField(blank=True, default='', max_length=500)),
                ('Pr_OnC_Percentage', models.CharField(blank=True, default='', max_length=500)),
                ('Portfolio', models.CharField(blank=True, default='', max_length=500)),
                ('PF_1', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Percentage1', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Provided1', models.BooleanField(default=False)),
                ('PF_Discussed1', models.BooleanField(default=False)),
                ('PF_2', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Percentage2', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Provided2', models.BooleanField(default=False)),
                ('PF_Discussed2', models.BooleanField(default=False)),
                ('PF_3', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Percentage3', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Provided3', models.BooleanField(default=False)),
                ('PF_Discussed3', models.BooleanField(default=False)),
                ('PF_4', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Percentage4', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Provided4', models.BooleanField(default=False)),
                ('PF_Discussed4', models.BooleanField(default=False)),
                ('PF_5', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Percentage5', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Provided5', models.BooleanField(default=False)),
                ('PF_Discussed5', models.BooleanField(default=False)),
                ('PF_6', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Percentage6', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Provided6', models.BooleanField(default=False)),
                ('PF_Discussed6', models.BooleanField(default=False)),
                ('PF_7', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Percentage7', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Provided7', models.BooleanField(default=False)),
                ('PF_Discussed7', models.BooleanField(default=False)),
                ('PF_Reasons', models.CharField(blank=True, default='', max_length=500)),
                ('PF_MaterialAspects', models.CharField(blank=True, default='', max_length=500)),
                ('PF_Pr_Details', models.CharField(blank=True, default='', max_length=500)),
                ('PF_NominationOfBeneficiaries', models.CharField(blank=True, default='', max_length=500)),
                ('SourceOfFunds', models.CharField(blank=True, default='', max_length=500)),
                ('SourceOfFundsDetail', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_1',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_2',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_3',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_4',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_5',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_6',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_7',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed1',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed2',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed3',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed4',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed5',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed6',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Discussed7',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_MaterialAspects',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_NominationOfBeneficiaries',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage1',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage2',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage3',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage4',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage5',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage6',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Percentage7',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Pr_Details',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided1',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided2',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided3',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided4',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided5',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided6',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Provided7',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_PF_Reasons',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Portfolio',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_Beneficiary',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_ContractingParty',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_EAC',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_Escalation',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_IniC',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_IniC_Percentage',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_LivesAssured',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_Name',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_OnC',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_OnC_Percentage',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_PolicyNumber',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_Premium',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_PremiumFrequency',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_PremiumPayer',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_Provider',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_Pr_Taken',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_SourceOfFunds',
        ),
        migrations.RemoveField(
            model_name='assuranceinvestment',
            name='AI_SourceOfFundsDetail',
        ),
    ]
