# Generated by Django 4.1.2 on 2023-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0083_ai_producttaken_remove_assuranceinvestment_ai_pf_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EB_Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('BusB_CoverType', models.IntegerField(default=0)),
                ('BusB_Cover', models.IntegerField(default=0)),
                ('BusB_CoverDetails', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
