# Generated by Django 4.1.2 on 2023-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_rename_name_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_producttaken',
            name='PF_AdditionComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='ip_producttaken',
            name='ItP_FundsAdditionComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
