# Generated by Django 4.1.2 on 2023-05-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_ai_producttaken_pf_additioncomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_producttaken',
            name='PF_ExecutorFee',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='ai_producttaken',
            name='PF_InformationExplained',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='ai_producttaken',
            name='PF_ProductDetails',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='ip_producttaken',
            name='ItP_ExecutorFee',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='ip_producttaken',
            name='ItP_InformationExplained',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='ip_producttaken',
            name='ItP_NominationOfBeneficiaries',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='ip_producttaken',
            name='ItP_ProductDetails',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
