# Generated by Django 4.1.2 on 2023-05-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_remove_ai_producttaken_pf_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_producttaken',
            name='ProductTaken',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
