# Generated by Django 4.1.2 on 2023-05-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0091_alter_ar_producttaken_producttaken'),
    ]

    operations = [
        migrations.CreateModel(
            name='STIP_Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('General_TypeOfLoss', models.CharField(blank=True, default='', max_length=20000)),
                ('General_LossYear', models.CharField(blank=True, default='', max_length=20000)),
                ('General_LossAmount', models.CharField(blank=True, default='', max_length=20000)),
                ('General_LossInsurer', models.CharField(blank=True, default='', max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shortterminsurancepersonal',
            name='STIP_General_LossAmount',
        ),
        migrations.RemoveField(
            model_name='shortterminsurancepersonal',
            name='STIP_General_LossInsurer',
        ),
        migrations.RemoveField(
            model_name='shortterminsurancepersonal',
            name='STIP_General_LossYear',
        ),
        migrations.RemoveField(
            model_name='shortterminsurancepersonal',
            name='STIP_General_TypeOfLoss',
        ),
    ]
