# Generated by Django 4.1.2 on 2023-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_shortterminsurancecommerical_stic_buildcombined_addcomments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STIC_Sec_Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('Fire_Limit', models.CharField(blank=True, default='', max_length=50)),
                ('Fire_ItemNumber', models.CharField(blank=True, default='', max_length=50)),
                ('Fire_Premium', models.CharField(blank=True, default='', max_length=50)),
                ('Fire_PremNumber', models.CharField(blank=True, default='', max_length=50)),
                ('Buildings_Insured', models.CharField(blank=True, default='', max_length=50)),
                ('Rental_Insured', models.CharField(blank=True, default='', max_length=50)),
                ('Others_Insured', models.CharField(blank=True, default='', max_length=50)),
                ('Stocks_Insured', models.CharField(blank=True, default='', max_length=50)),
                ('Miscellaneous1_Insured', models.CharField(blank=True, default='', max_length=50)),
                ('Miscellaneous2_Insured', models.CharField(blank=True, default='', max_length=50)),
                ('Earthquake_Insured', models.IntegerField(default='0')),
                ('Malicious_Damage_Insured', models.IntegerField(default='0')),
                ('Special_Insured', models.IntegerField(default='0')),
                ('LeakFull_Insured', models.IntegerField(default='0')),
                ('LeakFirst_Insured', models.IntegerField(default='0')),
                ('SnLLimited_Insured', models.IntegerField(default='0')),
                ('SnLComprehensive_Insured', models.IntegerField(default='0')),
                ('RnS_Insured', models.IntegerField(default='0')),
                ('SDC_Insured', models.IntegerField(default='0')),
                ('Fire_AddComments', models.CharField(blank=True, default='', max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
