# Generated by Django 4.1.2 on 2023-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0094_stic_sec_fire'),
    ]

    operations = [
        migrations.CreateModel(
            name='STIC_Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('General_TypeOfLoss', models.CharField(blank=True, default='', max_length=2000)),
                ('General_LossYear', models.CharField(blank=True, default='', max_length=2000)),
                ('General_LossAmount', models.CharField(blank=True, default='', max_length=2000)),
                ('General_LossInsurer', models.CharField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
