# Generated by Django 4.1.2 on 2023-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0096_form_clientreplacement_form_clientreplacementreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_AddProp_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_Build_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_DbyI_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_HC_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_LegalA_AddComments',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_MotorC_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_PersonalLL_AddComments',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_Trailer_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_Vehicle_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_WaterC_AddComments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
