# Generated by Django 4.1.2 on 2023-05-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0098_stic_sec_10_stic_sec_11_stic_sec_12_stic_sec_13_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_BenDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('BenDesc', models.CharField(blank=True, default='', max_length=20000)),
                ('BenDesc_CoverAmount', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='clientName',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
