# Generated by Django 4.1.2 on 2023-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_risk_bendesc_alter_form_clientname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover10',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover11',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover12',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover13',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover14',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover15',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover16',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover17',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover18',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover19',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover20',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover21',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover22',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover23',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover24',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover25',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover26',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover27',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover28',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover29',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover30',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover31',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover32',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover33',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover34',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover35',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover36',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover37',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover38',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover39',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover40',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover41',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover42',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover43',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover44',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover6',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover7',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover8',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shortterminsurancecommerical',
            name='STIC_ProdComp_ExistP_Cover9',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
