# Generated by Django 4.1.2 on 2023-06-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0103_shortterminsurancecommerical_stic_prodcomp_existp_cover1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_10_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_11_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_12_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_13_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_14_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_15_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_16_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_17_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_18_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_19_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_1_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_20_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_21_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_22_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_23_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_24_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_25_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_26_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_27_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_2_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_3_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_4_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_5_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_6_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_7_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_8_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_9_Cover',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
