# Generated by Django 4.1.2 on 2023-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0105_stip_sec_addprop_stip_sec_build_stip_sec_hc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='admin_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
