# Generated by Django 4.1.2 on 2023-06-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0106_alter_useraccount_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='admin_id',
        ),
    ]
