# Generated by Django 4.1.2 on 2023-06-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0107_remove_useraccount_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='admin_id',
            field=models.IntegerField(default=0),
        ),
    ]
