# Generated by Django 4.1.2 on 2023-06-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0108_useraccount_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_SecE_1',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_SecE_2',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='STIC_SecE_3',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
