# Generated by Django 4.1.2 on 2023-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0110_alter_risk_bendesc_bendesc_coveramount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_BnS_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('BnS_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('BnS_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('BnS_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('BnS_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('BnS_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='AR_BusOvProt_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('BusOvProt_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('BusOvProt_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('BusOvProt_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('BusOvProt_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('BusOvProt_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='AR_CLARedm_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('CLARedm_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('CLARedm_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('CLARedm_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('CLARedm_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('CLARedm_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='AR_DLARedm_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('DLARedm_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('DLARedm_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('DLARedm_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('DLARedm_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('DLARedm_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='AR_KeyP_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('KeyP_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('KeyP_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('KeyP_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('KeyP_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('KeyP_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='AR_SureNLia_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('SureNLia_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('SureNLia_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('SureNLia_OtherProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('SureNLia_OtherShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('SureNLia_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Risk_DC_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('DC_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('DC_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('DC_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('DC_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('DC_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Risk_DiC_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('DiC_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('DiC_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('DiC_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('DiC_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('DiC_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Risk_DrC_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('DrC_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('DrC_OtherTotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('DrC_OtherExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('DrC_OtherExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('DrC_OtherInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
    ]
