# Generated by Django 4.1.2 on 2023-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0111_ar_bns_others_ar_busovprot_others_ar_claredm_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='MSA_Advisor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
