# Generated by Django 4.1.2 on 2023-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0112_medical_msa_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('AI_Other', models.CharField(blank=True, default='', max_length=20000)),
                ('AI_Other_TotalNeed', models.CharField(blank=True, default='', max_length=20000)),
                ('AI_Other_ExistingProvisions', models.CharField(blank=True, default='', max_length=20000)),
                ('AI_Other_ExistingShortfallSurplus', models.CharField(blank=True, default='', max_length=20000)),
                ('AI_Other_ExistingInvestments', models.CharField(blank=True, default='', max_length=20000)),
            ],
        ),
    ]
