# Generated by Django 4.1.2 on 2023-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0113_ai_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ExecutorFee',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='InformationExplained',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='NominationOfBeneficiaries',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ProductDetails',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ProductMaterialAspects',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ProductReasons',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stic_loss',
            name='General_LossAmount',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stic_loss',
            name='General_LossInsurer',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stic_loss',
            name='General_LossYear',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stic_loss',
            name='General_TypeOfLoss',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stip_loss',
            name='General_LossAmount',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stip_loss',
            name='General_LossInsurer',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stip_loss',
            name='General_LossYear',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='stip_loss',
            name='General_TypeOfLoss',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
