# Generated by Django 4.1.2 on 2023-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0114_alter_rp_producttaken_executorfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='BenDesc_CoverAmount_7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ExecutorFee',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='InformationExplained',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='NominationOfBeneficiaries',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Policy_Number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ProductDetails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ProductMaterialAspects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='ProductReasons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_1stYearCommission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_2ndYearCommission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_Beneficiary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_ContractingParty',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_Escalation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_LivesAssured',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_Name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_OngoingFees',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_OngoingFeesFrequency',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_Pattern',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_Premium',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_PremiumPayer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_Provider',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='Product_Taken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='TotalFees_n_Commissions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
