# Generated by Django 4.1.2 on 2023-06-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0116_alter_ai_others_ai_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_10_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_11_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_12_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_13_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_14_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_15_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_16_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_17_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_18_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_19_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_1_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_20_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_21_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_22_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_23_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_24_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_25_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_26_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_27_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_2_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_3_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_4_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_5_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_6_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_7_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_8_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRI_9_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_10_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_11_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_12_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_13_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_14_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_15_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_16_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_17_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_18_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_19_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_1_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_20_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_21_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_22_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_23_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_24_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_25_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_26_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_27_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_2_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_3_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_4_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_5_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_6_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_7_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_8_Cover',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='STIP_CnRen_9_Cover',
            field=models.TextField(blank=True, default=''),
        ),
    ]
