# Generated by Django 4.1.2 on 2023-07-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0117_alter_shortterminsurancepersonal_stip_cnri_10_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='RF_Inception_Timeframe',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
