# Generated by Django 4.1.2 on 2023-07-11 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0118_riskfactors_rf_inception_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='Client_Individual_Risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Client_Legal_Risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Reputation_Risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Transaction_Inflow_Risk',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RF_Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Individual_Risk', models.IntegerField(default=0)),
                ('Client_Legal_Risk', models.IntegerField(default=0)),
                ('Transaction_Inflow_Risk', models.IntegerField(default=0)),
                ('Reputation_Risk', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.riskfactors')),
            ],
        ),
    ]
