# Generated by Django 4.1.2 on 2023-07-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0119_riskfactors_client_individual_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='Client_Individual_Risk_Label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Client_Legal_Risk_Label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Reputation_Risk_Label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Transaction_Inflow_Risk_Label',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
