# Generated by Django 4.1.2 on 2023-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0120_riskfactors_client_individual_risk_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfactors',
            name='Client_Individual_Risk_Label',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Client_Legal_Risk_Label',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Reputation_Risk_Label',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Transaction_Inflow_Risk_Label',
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Client_Individual_Risk_Level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Client_Legal_Risk_Level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Reputation_Risk_Level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='Transaction_Inflow_Risk_Level',
            field=models.FloatField(default=0),
        ),
    ]
