# Generated by Django 4.1.2 on 2023-07-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0121_remove_riskfactors_client_individual_risk_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='Transaction_Outflow_Risk_Level',
            field=models.FloatField(default=0),
        ),
    ]
