# Generated by Django 4.1.2 on 2023-07-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0122_riskfactors_transaction_outflow_risk_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfactors',
            name='Client_Individual_Risk',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Client_Individual_Risk_Level',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Client_Legal_Risk',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Client_Legal_Risk_Level',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Reputation_Risk',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Reputation_Risk_Level',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Transaction_Inflow_Risk',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Transaction_Inflow_Risk_Level',
        ),
        migrations.RemoveField(
            model_name='riskfactors',
            name='Transaction_Outflow_Risk_Level',
        ),
    ]
