# Generated by Django 4.1.2 on 2023-07-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0123_remove_riskfactors_client_individual_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='ClientIndividualRiskLevel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='ClientIndividualRiskScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='ClientLegalRiskLevel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='ClientLegalRiskLevelScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='DReputationRiskLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='TransactionInFlowRiskLevel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='TransactionInFlowRiskScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='TransactionOutFlowRiskLevel',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='TransactionOutFlowRiskScore',
            field=models.IntegerField(default=0),
        ),
    ]
