# Generated by Django 4.1.2 on 2023-08-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0126_riskfactors_policy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_arc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_gk',
            field=models.BooleanField(default=False),
        ),
    ]
