# Generated by Django 4.1.2 on 2023-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0127_useraccount_is_arc_useraccount_is_gk'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfactors',
            name='Commission',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
