# Generated by Django 4.1.2 on 2023-09-01 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0128_riskfactors_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='userType',
            field=models.IntegerField(choices=[(1, 'superadmin'), (2, 'arc'), (3, 'gk'), (4, 'manager'), (5, 'advisor')], default=5),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.TextField(default='')),
                ('initials', models.TextField(default='')),
                ('full_name', models.TextField(default='')),
                ('nick_name', models.TextField(default='')),
                ('contact_number', models.TextField(default='')),
                ('region', models.TextField(default='')),
                ('address_physical_1', models.TextField(default='')),
                ('address_physical_2', models.TextField(default='')),
                ('address_physical_3', models.TextField(default='')),
                ('address_postal_code', models.TextField(default='')),
                ('bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.bac')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
