# Generated by Django 4.1.2 on 2023-09-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0129_bac_useraccount_usertype_userprofile_advisors'),
    ]

    operations = [
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.TextField(default='')),
                ('initials', models.TextField(default='')),
                ('full_name', models.TextField(default='')),
                ('nick_name', models.TextField(default='')),
                ('contact_number', models.TextField(default='')),
                ('address_physical_1', models.TextField(default='')),
                ('address_physical_2', models.TextField(default='')),
                ('address_physical_3', models.TextField(default='')),
                ('address_postal_code', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bac',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_arc',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_gk',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='role',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='userType',
            field=models.IntegerField(choices=[(1, 'arc'), (2, 'gk'), (3, 'manager'), (4, 'advisor')], default=4),
        ),
        migrations.RenameModel(
            old_name='BAC',
            new_name='bac_model',
        ),
        migrations.DeleteModel(
            name='Advisors',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='bac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.bac_model'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.regions'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
