# Generated by Django 4.1.2 on 2023-09-08 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0130_regions_user_profile_remove_userprofile_bac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='userType',
            field=models.IntegerField(default=0),
        ),
    ]
