# Generated by Django 4.1.2 on 2023-09-08 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0131_alter_user_profile_bac_alter_useraccount_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='supervision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervision_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
