# Generated by Django 4.1.2 on 2023-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0132_user_profile_supervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address_physical_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='address_physical_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='address_physical_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='address_postal_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='contact_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='id_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='initials',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='nick_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
