# Generated by Django 4.1.2 on 2023-09-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0134_remove_user_profile_id_alter_user_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
