# Generated by Django 4.1.2 on 2023-09-13 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0135_delete_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.TextField(blank=True, default='', null=True)),
                ('initials', models.TextField(blank=True, default='', null=True)),
                ('full_name', models.TextField(default='')),
                ('nick_name', models.TextField(blank=True, default='', null=True)),
                ('contact_number', models.TextField(blank=True, default='', null=True)),
                ('address_physical_1', models.TextField(blank=True, default='', null=True)),
                ('address_physical_2', models.TextField(blank=True, default='', null=True)),
                ('address_physical_3', models.TextField(blank=True, default='', null=True)),
                ('address_postal_code', models.TextField(blank=True, default='', null=True)),
                ('bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_id', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_id', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.regions')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
