# Generated by Django 4.1.2 on 2023-09-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0136_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='supervision',
        ),
    ]
