# Generated by Django 4.1.2 on 2023-10-09 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0137_remove_user_profile_supervision'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorisation', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='supervision',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.riskfactors'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='bac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bac_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.regions'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='categorisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.categorisation'),
        ),
    ]
