# Generated by Django 4.1.2 on 2023-10-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0139_region_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='manager',
        ),
    ]
