# Generated by Django 4.1.2 on 2023-10-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0140_remove_user_profile_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
