# Generated by Django 4.1.2 on 2023-10-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0141_useraccount_is_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='flag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
