# Generated by Django 4.1.2 on 2023-10-31 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0142_user_profile_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='flag',
        ),
    ]
