# Generated by Django 4.1.2 on 2023-12-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0144_useraccount_sanport_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('client_name', models.TextField(default='')),
                ('client_id_number', models.TextField(blank=True, default='')),
                ('client_contact', models.TextField(blank=True, default='')),
                ('letter_of_introduction', models.IntegerField(default=0)),
                ('popi', models.IntegerField(default=0)),
                ('pi', models.IntegerField(default=0)),
                ('marketing_purposes', models.IntegerField(default=0)),
                ('pi_retained', models.IntegerField(default=0)),
                ('client_date', models.DateField(blank=True)),
                ('client_authorization_date', models.DateField(blank=True)),
                ('appointment_date', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisclosuresProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField(default=0)),
                ('formId', models.IntegerField(default=0)),
                ('product_provider', models.TextField(blank=True, default='')),
                ('product_provider1', models.TextField(blank=True, default='')),
                ('subcode', models.TextField(blank=True, default='')),
                ('subcode1', models.TextField(blank=True, default='')),
            ],
        ),
    ]
