# Generated by Django 4.1.2 on 2023-12-22 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0145_disclosures_disclosuresproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Address_Physical_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Address_Physical_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Address_Physical_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Address_Physical_Postal_Code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Address_Postal_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Address_Postal_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Address_Postal_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Address_Postal_Postal_Code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Apply_to_All_Categories',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Appointment_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_10_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_11_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_12_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_13_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_14_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_15_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_16_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_17_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_18_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_19_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_1_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_20_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_21_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_22_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_23_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_24_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_25_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_26_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_2_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_3_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_4_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_5_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_6_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_7_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_8_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_Accredited',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_FSB_Registration_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_First_Registration_Date_AdviceServices',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_First_Registration_Date_Intm_Services',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_Registration_Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_Services_Under_Supervision_End_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_Services_Under_Supervision_Start_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category1_9_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_10_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_11_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_12_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_13_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_14_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_15_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_16_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_17_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_18_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_19_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_1_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_20_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_21_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_22_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_23_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_24_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_25_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_26_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_2_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_3_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_4_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_5_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_6_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_7_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_8_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Category_1_9_SUS_Completion_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Contact_Cell',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Contact_Fax',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Contact_Telephone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Created_By',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Created_By_Delegate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Created_On',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='DOFA',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Debarred_Reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Decision_to_Debar_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Default_Supervisor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Disciplinary_Hearing_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Employee_Code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='FSP',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='FSP_option',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_1_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_1_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_1_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_BA_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_BA_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_BA_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_Estate_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_Estate_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_Estate_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_Inv_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_Inv_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_2_Inv_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_3_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_3_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Financial_Planning_3_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='First_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Full_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Fullname_Concatunated',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='ID_Number',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Initials',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Intermediary_Code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Investment_Category_option',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Juristic_Contract',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Modified_By',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Modified_By_Delegate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Modified_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Nick_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Owner',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Owning_Business_Unit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Race_option',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Receipt_of_Confiormation_from_FSB_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Record_Created_On',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Referral_to_FSB_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Regulatory_Exams_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Regulatory_Exams_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Regulatory_Exams_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Representative_Status_option',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Resignation_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Role',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Status_Reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Surname',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Temp_Full_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Test_Full_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Broker_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_1_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_1_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_1_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_2_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_2_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_2_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_3_Cutoff_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_3_Indicator',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Wealth_Management_3_Obtained_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Years_of_Service',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
