# Generated by Django 4.1.2 on 2023-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0149_alter_user_profile_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosures',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
