# Generated by Django 4.1.2 on 2023-12-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0150_disclosures_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disclosures',
            old_name='pi',
            new_name='pi_processing',
        ),
        migrations.AddField(
            model_name='disclosures',
            name='policy_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disclosures',
            name='provider_for',
            field=models.IntegerField(default=0),
        ),
    ]
