# Generated by Django 4.1.2 on 2023-12-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0151_rename_pi_disclosures_pi_processing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosures',
            name='existingClient',
            field=models.IntegerField(default=0),
        ),
    ]
