# Generated by Django 4.1.2 on 2023-12-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0152_disclosures_existingclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disclosuresproducts',
            name='product_provider1',
        ),
        migrations.RemoveField(
            model_name='disclosuresproducts',
            name='subcode1',
        ),
    ]
