# Generated by Django 4.1.2 on 2023-12-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0154_disclosuresproductproviders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosuresproductproviders',
            name='product_type',
            field=models.TextField(default=2),
        ),
    ]
