# Generated by Django 4.1.2 on 2023-12-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0155_disclosuresproductproviders_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosuresproductproviders',
            name='product_type',
            field=models.TextField(default=1),
        ),
    ]
