# Generated by Django 4.1.2 on 2023-12-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0157_alter_disclosuresproductproviders_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosures',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
