# Generated by Django 4.1.2 on 2024-01-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0158_disclosures_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Qualification_Name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
