# Generated by Django 4.1.2 on 2024-01-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0160_alter_ai_producttaken_pr_premiumfrequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_CountryOfBirth_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_CountryOfOperation_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_CountryOfRegistration_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_CountryOfResidence_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_High_Transaction_Reason_Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_Nationality_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_Transaction_Method_Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_Transaction_Reason_Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rf_scores',
            name='RF_Type_Legal_Entity_Score',
            field=models.IntegerField(default=0),
        ),
    ]
