# Generated by Django 4.1.2 on 2024-01-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0161_alter_rf_scores_rf_countryofbirth_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PremiumType',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_ReturnRequired',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Strategy',
            field=models.IntegerField(default=2),
        ),
    ]
