# Generated by Django 4.1.2 on 2024-01-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0162_alter_assuranceinvestment_ai_premiumtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_RiskProfile',
            field=models.IntegerField(default=2),
        ),
    ]
