# Generated by Django 4.1.2 on 2024-01-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0163_alter_assuranceinvestment_ai_riskprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_PremiumType',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_ReturnRequired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_RiskProfile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='AI_Strategy',
            field=models.IntegerField(default=0),
        ),
    ]
