# Generated by Django 4.1.2 on 2024-01-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0165_alter_ai_producttaken_pr_premiumfrequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Appointment_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_10_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_10_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_10_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_10_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_10_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_11_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_11_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_11_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_11_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_11_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_12_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_12_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_12_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_12_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_12_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_13_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_13_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_13_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_13_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_13_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_14_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_14_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_14_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_14_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_14_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_15_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_15_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_15_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_15_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_15_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_16_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_16_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_16_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_16_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_16_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_17_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_17_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_17_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_17_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_17_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_18_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_18_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_18_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_18_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_18_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_19_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_19_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_19_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_19_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_19_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_1_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_1_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_1_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_1_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_1_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_20_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_20_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_20_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_20_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_20_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_21_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_21_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_21_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_21_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_21_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_22_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_22_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_22_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_22_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_22_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_23_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_23_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_23_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_23_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_23_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_24_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_24_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_24_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_24_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_24_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_25_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_25_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_25_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_25_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_25_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_26_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_26_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_26_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_26_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_26_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_2_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_2_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_2_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_2_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_2_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_3_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_3_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_3_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_3_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_3_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_4_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_4_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_4_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_4_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_4_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_5_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_5_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_5_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_5_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_5_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_6_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_6_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_6_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_6_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_6_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_7_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_7_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_7_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_7_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_7_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_8_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_8_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_8_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_8_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_8_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_9_FSB_Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_9_First_Registration_Date_AdviceServices',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_9_First_Registration_Date_Intm_Services',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_9_Services_Under_Supervision_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category1_9_Services_Under_Supervision_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_10_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_11_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_12_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_13_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_14_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_15_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_16_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_17_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_18_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_19_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_1_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_20_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_21_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_22_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_23_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_24_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_25_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_26_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_2_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_3_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_4_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_5_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_6_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_7_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_8_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Category_1_9_SUS_Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Created_On',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='DOFA',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Decision_to_Debar_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Disciplinary_Hearing_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_1_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_1_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_2_BA_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_2_BA_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_2_Estate_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_2_Estate_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_2_Inv_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_2_Inv_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_3_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Financial_Planning_3_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Modified_On',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Receipt_of_Confiormation_from_FSB_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Record_Created_On',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Referral_to_FSB_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Regulatory_Exams_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Regulatory_Exams_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Resignation_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Wealth_Management_1_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Wealth_Management_1_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Wealth_Management_2_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Wealth_Management_2_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Wealth_Management_3_Cutoff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Wealth_Management_3_Obtained_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
