# Generated by Django 4.1.2 on 2024-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0166_alter_user_profile_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='Created_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Modified_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='Record_Created_On',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
