# Generated by Django 4.1.2 on 2024-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0168_alter_user_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='Advisor_Tag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
