# Generated by Django 4.1.2 on 2024-01-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0170_disclosuresadvisorsubcodes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='EB_BusRB_DiIBenWaitPer_Category4',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
