# Generated by Django 4.1.2 on 2024-02-12 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0171_alter_employeebenefits_eb_busrb_diibenwaitper_category1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosuresproductproviders',
            name='product_code',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='disclosuresproducts',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disclosuresproducts',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
    ]
