# Generated by Django 4.1.2 on 2024-02-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0172_disclosuresproductproviders_product_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disclosuresproductproviders',
            old_name='product_code',
            new_name='product_subcode',
        ),
    ]
