# Generated by Django 4.1.2 on 2024-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0173_rename_product_code_disclosuresproductproviders_product_subcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosuresproductproviders',
            name='product_subcode',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
