# Generated by Django 4.1.2 on 2024-02-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0174_alter_disclosuresproductproviders_product_subcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disclosuresproducts',
            name='advisorId',
        ),
        migrations.RemoveField(
            model_name='disclosuresproducts',
            name='subcode',
        ),
        migrations.AlterField(
            model_name='disclosuresproducts',
            name='product_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosuresproductproviders'),
        ),
    ]
