# Generated by Django 4.1.2 on 2024-02-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0176_disclosuresproducts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosuresproducts',
            name='product_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.disclosuresadvisorsubcodes'),
        ),
    ]
