# Generated by Django 4.1.2 on 2024-02-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0177_alter_disclosuresproducts_product_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='BI_ACCESS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='CVP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='DDTC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='DEP_Sign_Up',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='DEP_URL',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='FB_URL',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='GROUP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='LI_URL',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='LMS_ACCESS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='LinkedIn_manage_profile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='OTP_Enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='PROFILEME_DBC_LINK',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='RE_ROLL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='user_comission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(blank=True, default='', null=True)),
                ('commission', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
