# Generated by Django 4.1.2 on 2024-03-04 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0178_user_profile_bi_access_user_profile_cvp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ai_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ai_producttaken',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ai_producttaken',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ar_bns_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_bns_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ar_busovprot_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_busovprot_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ar_claredm_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_claredm_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ar_dlaredm_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_dlaredm_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ar_keyp_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_keyp_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ar_producttaken',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_producttaken',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='ar_surenlia_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ar_surenlia_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='assuranceinvestment',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assurancerisk',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disclosures',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eb_cover',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eb_cover',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='employeebenefits',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='gapcover',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investmentplanning',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ip_producttaken',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ip_producttaken',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rf_linkedparty',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rf_linkedparty',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='risk_bendesc',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk_bendesc',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='risk_dc_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk_dc_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='risk_dic_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk_dic_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='risk_drc_others',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk_drc_others',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskplanning',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rp_producttaken',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='rp_producttaken_bendesc',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rp_producttaken_bendesc',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='shortterminsurancecommerical',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortterminsurancepersonal',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_loss',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_loss',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_10',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_10',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_11',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_11',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_12',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_12',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_13',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_13',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_14',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_14',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_15',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_15',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_16',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_16',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_17',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_17',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_18',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_18',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_19',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_19',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_2',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_2',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_20',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_20',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_21',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_21',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_3',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_3',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_4',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_4',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_5',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_5',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_6',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_6',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_7',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_7',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_8',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_8',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_9',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_9',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stic_sec_fire',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stic_sec_fire',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_loss',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_loss',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_addprop',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_addprop',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_build',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_build',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_hc',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_hc',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_legala',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_legala',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_motorc',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_motorc',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_personalll',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_personalll',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_trailer',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_trailer',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_vehicle',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_vehicle',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
        migrations.AlterField(
            model_name='stip_sec_waterc',
            name='advisorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stip_sec_waterc',
            name='formId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.disclosures'),
        ),
    ]
