# Generated by Django 4.1.2 on 2024-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0179_alter_ai_others_advisorid_alter_ai_others_formid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='clientDateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
