# Generated by Django 4.1.2 on 2024-03-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0180_alter_form_clientdateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='address_physical_1',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='address_physical_2',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='address_physical_3',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='address_postal_code',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='initials',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='nick_name',
        ),
    ]
