# Generated by Django 4.1.2 on 2022-10-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_update1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskplanning',
            old_name='RPLifeCoverFinancialSolutions',
            new_name='RP_LC_FinancialSolutions',
        ),
    ]
