# Generated by Django 4.1.2 on 2022-10-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_update1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assuranceinvestment',
            old_name='AI_RA_Investments',
            new_name='AI_RA_ExistingInvestments',
        ),
    ]
