# Generated by Django 4.1.2 on 2022-10-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_update2_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_CLARedm_OtherExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_CLARedm_OtherExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_CLARedm_OtherInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_CLARedm_OtherTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_DLARedm_OtherExistingProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_DLARedm_OtherExistingShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_DLARedm_OtherInvestments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_DLARedm_OtherTotalNeed',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
