# Generated by Django 4.1.2 on 2022-10-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_update2_1_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherExistingProvisions',
        ),
        migrations.RemoveField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherExistingShortfallSurplus',
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherProvisions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assurancerisk',
            name='AR_SureNLia_OtherShortfallSurplus',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
