# Generated by Django 4.1.2 on 2024-01-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcontent',
            name='downloading_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
