# Generated by Django 4.1.2 on 2022-10-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_changed_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='admin',
            field=models.IntegerField(default=0),
        ),
    ]
