# Generated by Django 4.1.2 on 2022-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_changed_my_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='admin',
            new_name='admin_id',
        ),
    ]
