# Generated by Django 4.1.2 on 2022-10-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_added_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='partial_password',
            field=models.BooleanField(default=True),
        ),
    ]
