# Generated by Django 4.1.2 on 2022-10-25 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_advisorIDUpdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='client_background_info',
            new_name='clientBackgroundInfo',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='client_fica',
            new_name='clientFica',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='client_fica_reason',
            new_name='clientFicaReason',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='client_letter_of_introduction',
            new_name='clientletterOfIntroduction',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='client_letter_of_introduction_reason',
            new_name='clientletterOfIntroductionAccessReason',
        ),
        migrations.RemoveField(
            model_name='form',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='form',
            name='client_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='form',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='form',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='form',
            name='client_name',
        ),
        migrations.AddField(
            model_name='form',
            name='clientAddress',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='form',
            name='clientDateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='form',
            name='clientEmail',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='form',
            name='clientIdNumber',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='form',
            name='clientName',
            field=models.CharField(default='John Doe', max_length=256),
        ),
        migrations.AddField(
            model_name='form',
            name='clientPhoneNumber',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='form',
            name='clientletterOfIntroductionAccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='clientletterOfIntroductionReason',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
