# Generated by Django 4.1.2 on 2022-10-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_FormUpdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='clientFica',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientletterOfIntroduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientletterOfIntroductionAccess',
            field=models.IntegerField(default=0),
        ),
    ]
