# Generated by Django 4.1.2 on 2022-10-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_FormUpdate1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='clientFicaReason',
            field=models.CharField(default='N.A.', max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientletterOfIntroductionAccessReason',
            field=models.CharField(default='N.A.', max_length=256),
        ),
        migrations.AlterField(
            model_name='form',
            name='clientletterOfIntroductionReason',
            field=models.CharField(default='N.A.', max_length=256),
        ),
    ]
