# Generated by Django 4.1.2 on 2022-10-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_FormUpdate2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='clientletterOfIntroduction',
            new_name='clientLetterOfIntroduction',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='clientletterOfIntroductionAccess',
            new_name='clientLetterOfIntroductionAccess',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='clientletterOfIntroductionAccessReason',
            new_name='clientLetterOfIntroductionAccessReason',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='clientletterOfIntroductionReason',
            new_name='clientLetterOfIntroductionReason',
        ),
    ]
