# Generated by Django 4.1.2 on 2022-10-25 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_FormUpdate3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiduciary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorId', models.IntegerField()),
                ('formId', models.IntegerField()),
                ('clientIdNumber', models.CharField(default='', max_length=256)),
                ('fiduciaryWillInPlace', models.IntegerField(default=0)),
                ('fiduciaryWillUpdataionDate', models.DateField(default=datetime.date.today)),
                ('fiduciaryWillKeepingPlace', models.CharField(default='N.A.', max_length=500)),
                ('fiduciaryExecutorDetails', models.CharField(default='N.A.', max_length=500)),
                ('fiduciaryClientInstructions', models.CharField(default='N.A.', max_length=500)),
                ('fiduciaryConsequencesExplained', models.CharField(default='N.A.', max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
