# Generated by Django 4.1.2 on 2022-10-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_fiduciary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiduciary',
            old_name='fiduciaryWillUpdataionDate',
            new_name='fiduciaryWillUpdationDate',
        ),
    ]
