# Generated by Django 4.1.2 on 2022-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_fiduciaryUpdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryClientInstructions',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryConsequencesExplained',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryExecutorDetails',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryWillKeepingPlace',
            field=models.CharField(blank=True, default='N.A.', max_length=500),
        ),
    ]
