# Generated by Django 4.1.2 on 2022-10-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_fiduciaryUpdate1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiduciary',
            name='fiduciaryWillUpdationDate',
            field=models.CharField(default='N.A.', max_length=500),
        ),
    ]
